/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as WorkRouteImport } from './routes/work'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as RelationshipsRouteImport } from './routes/relationships'
import { Route as RecruitingRouteImport } from './routes/recruiting'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as MortgageRouteImport } from './routes/mortgage'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as FlavorsRouteImport } from './routes/flavors'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as BrowserWorkersRouteImport } from './routes/browser-workers'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntitiesIndexRouteImport } from './routes/entities.index'
import { Route as RecruitingUsageRouteImport } from './routes/recruiting_.usage'
import { Route as RecruitingShortlistsRouteImport } from './routes/recruiting_.shortlists'
import { Route as RecruitingSearchRouteImport } from './routes/recruiting_.search'
import { Route as RecruitingResultsRouteImport } from './routes/recruiting_.results'
import { Route as RecruitingPipelineRouteImport } from './routes/recruiting_.pipeline'
import { Route as RecruitingLinkedinRouteImport } from './routes/recruiting_.linkedin'
import { Route as RecruitingJobsRouteImport } from './routes/recruiting_.jobs'
import { Route as RecruitingCompareRouteImport } from './routes/recruiting_.compare'
import { Route as FlavorsNewRouteImport } from './routes/flavors.new'
import { Route as EntitiesDemoRouteImport } from './routes/entities.demo'
import { Route as EntitiesKindRouteImport } from './routes/entities.$kind'
import { Route as RecruitingCandidatesIdRouteImport } from './routes/recruiting_.candidates.$id'
import { Route as EntitiesKindIdRouteImport } from './routes/entities.$kind.$id'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsRoute = RelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingRoute = RecruitingRouteImport.update({
  id: '/recruiting',
  path: '/recruiting',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageRoute = MortgageRouteImport.update({
  id: '/mortgage',
  path: '/mortgage',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavorsRoute = FlavorsRouteImport.update({
  id: '/flavors',
  path: '/flavors',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserWorkersRoute = BrowserWorkersRouteImport.update({
  id: '/browser-workers',
  path: '/browser-workers',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntitiesRoute,
} as any)
const RecruitingUsageRoute = RecruitingUsageRouteImport.update({
  id: '/recruiting_/usage',
  path: '/recruiting/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingShortlistsRoute = RecruitingShortlistsRouteImport.update({
  id: '/recruiting_/shortlists',
  path: '/recruiting/shortlists',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingSearchRoute = RecruitingSearchRouteImport.update({
  id: '/recruiting_/search',
  path: '/recruiting/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingResultsRoute = RecruitingResultsRouteImport.update({
  id: '/recruiting_/results',
  path: '/recruiting/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingPipelineRoute = RecruitingPipelineRouteImport.update({
  id: '/recruiting_/pipeline',
  path: '/recruiting/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingLinkedinRoute = RecruitingLinkedinRouteImport.update({
  id: '/recruiting_/linkedin',
  path: '/recruiting/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingJobsRoute = RecruitingJobsRouteImport.update({
  id: '/recruiting_/jobs',
  path: '/recruiting/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingCompareRoute = RecruitingCompareRouteImport.update({
  id: '/recruiting_/compare',
  path: '/recruiting/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavorsNewRoute = FlavorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FlavorsRoute,
} as any)
const EntitiesDemoRoute = EntitiesDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => EntitiesRoute,
} as any)
const EntitiesKindRoute = EntitiesKindRouteImport.update({
  id: '/$kind',
  path: '/$kind',
  getParentRoute: () => EntitiesRoute,
} as any)
const RecruitingCandidatesIdRoute = RecruitingCandidatesIdRouteImport.update({
  id: '/recruiting_/candidates/$id',
  path: '/recruiting/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesKindIdRoute = EntitiesKindIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EntitiesKindRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/browser-workers': typeof BrowserWorkersRoute
  '/crm': typeof CrmRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/experiments': typeof ExperimentsRoute
  '/flavors': typeof FlavorsRouteWithChildren
  '/insurance': typeof InsuranceRoute
  '/knowledge': typeof KnowledgeRoute
  '/marketing': typeof MarketingRoute
  '/mortgage': typeof MortgageRoute
  '/predictions': typeof PredictionsRoute
  '/projects': typeof ProjectsRoute
  '/real-estate': typeof RealEstateRoute
  '/recruiting': typeof RecruitingRoute
  '/relationships': typeof RelationshipsRoute
  '/success': typeof SuccessRoute
  '/tasks': typeof TasksRoute
  '/work': typeof WorkRoute
  '/workers': typeof WorkersRoute
  '/entities/$kind': typeof EntitiesKindRouteWithChildren
  '/entities/demo': typeof EntitiesDemoRoute
  '/flavors/new': typeof FlavorsNewRoute
  '/recruiting/compare': typeof RecruitingCompareRoute
  '/recruiting/jobs': typeof RecruitingJobsRoute
  '/recruiting/linkedin': typeof RecruitingLinkedinRoute
  '/recruiting/pipeline': typeof RecruitingPipelineRoute
  '/recruiting/results': typeof RecruitingResultsRoute
  '/recruiting/search': typeof RecruitingSearchRoute
  '/recruiting/shortlists': typeof RecruitingShortlistsRoute
  '/recruiting/usage': typeof RecruitingUsageRoute
  '/entities/': typeof EntitiesIndexRoute
  '/entities/$kind/$id': typeof EntitiesKindIdRoute
  '/recruiting/candidates/$id': typeof RecruitingCandidatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/browser-workers': typeof BrowserWorkersRoute
  '/crm': typeof CrmRoute
  '/experiments': typeof ExperimentsRoute
  '/flavors': typeof FlavorsRouteWithChildren
  '/insurance': typeof InsuranceRoute
  '/knowledge': typeof KnowledgeRoute
  '/marketing': typeof MarketingRoute
  '/mortgage': typeof MortgageRoute
  '/predictions': typeof PredictionsRoute
  '/projects': typeof ProjectsRoute
  '/real-estate': typeof RealEstateRoute
  '/recruiting': typeof RecruitingRoute
  '/relationships': typeof RelationshipsRoute
  '/success': typeof SuccessRoute
  '/tasks': typeof TasksRoute
  '/work': typeof WorkRoute
  '/workers': typeof WorkersRoute
  '/entities/$kind': typeof EntitiesKindRouteWithChildren
  '/entities/demo': typeof EntitiesDemoRoute
  '/flavors/new': typeof FlavorsNewRoute
  '/recruiting/compare': typeof RecruitingCompareRoute
  '/recruiting/jobs': typeof RecruitingJobsRoute
  '/recruiting/linkedin': typeof RecruitingLinkedinRoute
  '/recruiting/pipeline': typeof RecruitingPipelineRoute
  '/recruiting/results': typeof RecruitingResultsRoute
  '/recruiting/search': typeof RecruitingSearchRoute
  '/recruiting/shortlists': typeof RecruitingShortlistsRoute
  '/recruiting/usage': typeof RecruitingUsageRoute
  '/entities': typeof EntitiesIndexRoute
  '/entities/$kind/$id': typeof EntitiesKindIdRoute
  '/recruiting/candidates/$id': typeof RecruitingCandidatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/browser-workers': typeof BrowserWorkersRoute
  '/crm': typeof CrmRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/experiments': typeof ExperimentsRoute
  '/flavors': typeof FlavorsRouteWithChildren
  '/insurance': typeof InsuranceRoute
  '/knowledge': typeof KnowledgeRoute
  '/marketing': typeof MarketingRoute
  '/mortgage': typeof MortgageRoute
  '/predictions': typeof PredictionsRoute
  '/projects': typeof ProjectsRoute
  '/real-estate': typeof RealEstateRoute
  '/recruiting': typeof RecruitingRoute
  '/relationships': typeof RelationshipsRoute
  '/success': typeof SuccessRoute
  '/tasks': typeof TasksRoute
  '/work': typeof WorkRoute
  '/workers': typeof WorkersRoute
  '/entities/$kind': typeof EntitiesKindRouteWithChildren
  '/entities/demo': typeof EntitiesDemoRoute
  '/flavors/new': typeof FlavorsNewRoute
  '/recruiting_/compare': typeof RecruitingCompareRoute
  '/recruiting_/jobs': typeof RecruitingJobsRoute
  '/recruiting_/linkedin': typeof RecruitingLinkedinRoute
  '/recruiting_/pipeline': typeof RecruitingPipelineRoute
  '/recruiting_/results': typeof RecruitingResultsRoute
  '/recruiting_/search': typeof RecruitingSearchRoute
  '/recruiting_/shortlists': typeof RecruitingShortlistsRoute
  '/recruiting_/usage': typeof RecruitingUsageRoute
  '/entities/': typeof EntitiesIndexRoute
  '/entities/$kind/$id': typeof EntitiesKindIdRoute
  '/recruiting_/candidates/$id': typeof RecruitingCandidatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliate'
    | '/browser-workers'
    | '/crm'
    | '/entities'
    | '/experiments'
    | '/flavors'
    | '/insurance'
    | '/knowledge'
    | '/marketing'
    | '/mortgage'
    | '/predictions'
    | '/projects'
    | '/real-estate'
    | '/recruiting'
    | '/relationships'
    | '/success'
    | '/tasks'
    | '/work'
    | '/workers'
    | '/entities/$kind'
    | '/entities/demo'
    | '/flavors/new'
    | '/recruiting/compare'
    | '/recruiting/jobs'
    | '/recruiting/linkedin'
    | '/recruiting/pipeline'
    | '/recruiting/results'
    | '/recruiting/search'
    | '/recruiting/shortlists'
    | '/recruiting/usage'
    | '/entities/'
    | '/entities/$kind/$id'
    | '/recruiting/candidates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate'
    | '/browser-workers'
    | '/crm'
    | '/experiments'
    | '/flavors'
    | '/insurance'
    | '/knowledge'
    | '/marketing'
    | '/mortgage'
    | '/predictions'
    | '/projects'
    | '/real-estate'
    | '/recruiting'
    | '/relationships'
    | '/success'
    | '/tasks'
    | '/work'
    | '/workers'
    | '/entities/$kind'
    | '/entities/demo'
    | '/flavors/new'
    | '/recruiting/compare'
    | '/recruiting/jobs'
    | '/recruiting/linkedin'
    | '/recruiting/pipeline'
    | '/recruiting/results'
    | '/recruiting/search'
    | '/recruiting/shortlists'
    | '/recruiting/usage'
    | '/entities'
    | '/entities/$kind/$id'
    | '/recruiting/candidates/$id'
  id:
    | '__root__'
    | '/'
    | '/affiliate'
    | '/browser-workers'
    | '/crm'
    | '/entities'
    | '/experiments'
    | '/flavors'
    | '/insurance'
    | '/knowledge'
    | '/marketing'
    | '/mortgage'
    | '/predictions'
    | '/projects'
    | '/real-estate'
    | '/recruiting'
    | '/relationships'
    | '/success'
    | '/tasks'
    | '/work'
    | '/workers'
    | '/entities/$kind'
    | '/entities/demo'
    | '/flavors/new'
    | '/recruiting_/compare'
    | '/recruiting_/jobs'
    | '/recruiting_/linkedin'
    | '/recruiting_/pipeline'
    | '/recruiting_/results'
    | '/recruiting_/search'
    | '/recruiting_/shortlists'
    | '/recruiting_/usage'
    | '/entities/'
    | '/entities/$kind/$id'
    | '/recruiting_/candidates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliateRoute: typeof AffiliateRoute
  BrowserWorkersRoute: typeof BrowserWorkersRoute
  CrmRoute: typeof CrmRoute
  EntitiesRoute: typeof EntitiesRouteWithChildren
  ExperimentsRoute: typeof ExperimentsRoute
  FlavorsRoute: typeof FlavorsRouteWithChildren
  InsuranceRoute: typeof InsuranceRoute
  KnowledgeRoute: typeof KnowledgeRoute
  MarketingRoute: typeof MarketingRoute
  MortgageRoute: typeof MortgageRoute
  PredictionsRoute: typeof PredictionsRoute
  ProjectsRoute: typeof ProjectsRoute
  RealEstateRoute: typeof RealEstateRoute
  RecruitingRoute: typeof RecruitingRoute
  RelationshipsRoute: typeof RelationshipsRoute
  SuccessRoute: typeof SuccessRoute
  TasksRoute: typeof TasksRoute
  WorkRoute: typeof WorkRoute
  WorkersRoute: typeof WorkersRoute
  RecruitingCompareRoute: typeof RecruitingCompareRoute
  RecruitingJobsRoute: typeof RecruitingJobsRoute
  RecruitingLinkedinRoute: typeof RecruitingLinkedinRoute
  RecruitingPipelineRoute: typeof RecruitingPipelineRoute
  RecruitingResultsRoute: typeof RecruitingResultsRoute
  RecruitingSearchRoute: typeof RecruitingSearchRoute
  RecruitingShortlistsRoute: typeof RecruitingShortlistsRoute
  RecruitingUsageRoute: typeof RecruitingUsageRoute
  RecruitingCandidatesIdRoute: typeof RecruitingCandidatesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships': {
      id: '/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting': {
      id: '/recruiting'
      path: '/recruiting'
      fullPath: '/recruiting'
      preLoaderRoute: typeof RecruitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage': {
      id: '/mortgage'
      path: '/mortgage'
      fullPath: '/mortgage'
      preLoaderRoute: typeof MortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavors': {
      id: '/flavors'
      path: '/flavors'
      fullPath: '/flavors'
      preLoaderRoute: typeof FlavorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser-workers': {
      id: '/browser-workers'
      path: '/browser-workers'
      fullPath: '/browser-workers'
      preLoaderRoute: typeof BrowserWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/': {
      id: '/entities/'
      path: '/'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/recruiting_/usage': {
      id: '/recruiting_/usage'
      path: '/recruiting/usage'
      fullPath: '/recruiting/usage'
      preLoaderRoute: typeof RecruitingUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting_/shortlists': {
      id: '/recruiting_/shortlists'
      path: '/recruiting/shortlists'
      fullPath: '/recruiting/shortlists'
      preLoaderRoute: typeof RecruitingShortlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting_/search': {
      id: '/recruiting_/search'
      path: '/recruiting/search'
      fullPath: '/recruiting/search'
      preLoaderRoute: typeof RecruitingSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting_/results': {
      id: '/recruiting_/results'
      path: '/recruiting/results'
      fullPath: '/recruiting/results'
      preLoaderRoute: typeof RecruitingResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting_/pipeline': {
      id: '/recruiting_/pipeline'
      path: '/recruiting/pipeline'
      fullPath: '/recruiting/pipeline'
      preLoaderRoute: typeof RecruitingPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting_/linkedin': {
      id: '/recruiting_/linkedin'
      path: '/recruiting/linkedin'
      fullPath: '/recruiting/linkedin'
      preLoaderRoute: typeof RecruitingLinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting_/jobs': {
      id: '/recruiting_/jobs'
      path: '/recruiting/jobs'
      fullPath: '/recruiting/jobs'
      preLoaderRoute: typeof RecruitingJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting_/compare': {
      id: '/recruiting_/compare'
      path: '/recruiting/compare'
      fullPath: '/recruiting/compare'
      preLoaderRoute: typeof RecruitingCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavors/new': {
      id: '/flavors/new'
      path: '/new'
      fullPath: '/flavors/new'
      preLoaderRoute: typeof FlavorsNewRouteImport
      parentRoute: typeof FlavorsRoute
    }
    '/entities/demo': {
      id: '/entities/demo'
      path: '/demo'
      fullPath: '/entities/demo'
      preLoaderRoute: typeof EntitiesDemoRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/entities/$kind': {
      id: '/entities/$kind'
      path: '/$kind'
      fullPath: '/entities/$kind'
      preLoaderRoute: typeof EntitiesKindRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/recruiting_/candidates/$id': {
      id: '/recruiting_/candidates/$id'
      path: '/recruiting/candidates/$id'
      fullPath: '/recruiting/candidates/$id'
      preLoaderRoute: typeof RecruitingCandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$kind/$id': {
      id: '/entities/$kind/$id'
      path: '/$id'
      fullPath: '/entities/$kind/$id'
      preLoaderRoute: typeof EntitiesKindIdRouteImport
      parentRoute: typeof EntitiesKindRoute
    }
  }
}

interface EntitiesKindRouteChildren {
  EntitiesKindIdRoute: typeof EntitiesKindIdRoute
}

const EntitiesKindRouteChildren: EntitiesKindRouteChildren = {
  EntitiesKindIdRoute: EntitiesKindIdRoute,
}

const EntitiesKindRouteWithChildren = EntitiesKindRoute._addFileChildren(
  EntitiesKindRouteChildren,
)

interface EntitiesRouteChildren {
  EntitiesKindRoute: typeof EntitiesKindRouteWithChildren
  EntitiesDemoRoute: typeof EntitiesDemoRoute
  EntitiesIndexRoute: typeof EntitiesIndexRoute
}

const EntitiesRouteChildren: EntitiesRouteChildren = {
  EntitiesKindRoute: EntitiesKindRouteWithChildren,
  EntitiesDemoRoute: EntitiesDemoRoute,
  EntitiesIndexRoute: EntitiesIndexRoute,
}

const EntitiesRouteWithChildren = EntitiesRoute._addFileChildren(
  EntitiesRouteChildren,
)

interface FlavorsRouteChildren {
  FlavorsNewRoute: typeof FlavorsNewRoute
}

const FlavorsRouteChildren: FlavorsRouteChildren = {
  FlavorsNewRoute: FlavorsNewRoute,
}

const FlavorsRouteWithChildren =
  FlavorsRoute._addFileChildren(FlavorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliateRoute: AffiliateRoute,
  BrowserWorkersRoute: BrowserWorkersRoute,
  CrmRoute: CrmRoute,
  EntitiesRoute: EntitiesRouteWithChildren,
  ExperimentsRoute: ExperimentsRoute,
  FlavorsRoute: FlavorsRouteWithChildren,
  InsuranceRoute: InsuranceRoute,
  KnowledgeRoute: KnowledgeRoute,
  MarketingRoute: MarketingRoute,
  MortgageRoute: MortgageRoute,
  PredictionsRoute: PredictionsRoute,
  ProjectsRoute: ProjectsRoute,
  RealEstateRoute: RealEstateRoute,
  RecruitingRoute: RecruitingRoute,
  RelationshipsRoute: RelationshipsRoute,
  SuccessRoute: SuccessRoute,
  TasksRoute: TasksRoute,
  WorkRoute: WorkRoute,
  WorkersRoute: WorkersRoute,
  RecruitingCompareRoute: RecruitingCompareRoute,
  RecruitingJobsRoute: RecruitingJobsRoute,
  RecruitingLinkedinRoute: RecruitingLinkedinRoute,
  RecruitingPipelineRoute: RecruitingPipelineRoute,
  RecruitingResultsRoute: RecruitingResultsRoute,
  RecruitingSearchRoute: RecruitingSearchRoute,
  RecruitingShortlistsRoute: RecruitingShortlistsRoute,
  RecruitingUsageRoute: RecruitingUsageRoute,
  RecruitingCandidatesIdRoute: RecruitingCandidatesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
